name: student_dashboard
description: CMPE 137 Assignment 1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  google_fonts: ^6.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/profile.jpeg